_target_: deepreaction.layer.mpnn_layer.gatv2_layer.GATv2Layer
in_channels: ${model.layer.hidden_channels}
out_channels: ${eval:'${model.layer.hidden_channels} // ${.heads}'}
heads: 4
dropout: 0.05
concat: true
use_edge_attr: true
