_target_: deepreaction.layer.mpnn_layer.pna_layer.PNALayer
in_channels: ${model.layer.hidden_channels}
out_channels: ${model.layer.hidden_channels}
aggregators: ['mean', 'max', 'sum'] # ['mean', 'max', 'min', 'std']
scalers: ['identity'] # ['identity', 'amplification', 'attenuation']
use_edge_attr: true
degree_statistics: ${degree_statistics}
