_target_: deepreaction.routine.supervised_learning_routine.SupervisedLearningRoutine
_partial_: true   # model passed at runtime

defaults:
  - loss: mse
  - optimizer: adamw
  - lr_scheduler: cosine_with_warmup

metrics: 
  _target_: torchmetrics.MetricCollection
  metrics: 
    - _target_: torchmetrics.MeanSquaredError
      squared: false
    - _target_: torchmetrics.MeanAbsoluteError

# Optional parameters:
# pretrained_path: null
# resume_training: false
# standardizer_path: null
