_target_: deeprxn.layer.att_layer.react_prod_att_layer.ReactantProductAttLayer
in_channels: ${model.hidden_channels}
out_channels: ${model.hidden_channels}
hidden_size: ${model.hidden_channels}
attention: reactants_products # reactants, products, reactants_products
num_heads: 3
dropout: 0.02
layer_norm: true
batch_norm: false
