_target_: deeprxn.layer.gps_layer.GPSLayer
_recursive_: False

defaults:
  - mpnn_cfg: gatedgcn_layer
  - att_layer_cfg: transformer

layer_norm: False
batch_norm: True
dropout: 0.0

in_channels: ${model.hidden_channels}
out_channels: ${model.hidden_channels}

att_layer_cfg:
  embed_dim: ${model.hidden_channels}
  num_heads: 4
  dropout: 0.5
