_target_: deeprxn.layer.mpnn_layer.pna_layer.PNALayer
in_channels: ${model.hidden_channels}
out_channels: ${model.hidden_channels}
aggregators: ['mean', 'max', 'sum'] # ['mean', 'max', 'min', 'std']
scalers: ['identity'] # ['identity', 'amplification', 'attenuation']
