_target_: deepreaction.model.gatedgcn.GatedGCN
_recursive_: False

defaults:
  - encoder_cfg:
    - linear_node_enc
    - linear_edge_enc
  - layer_cfg: block_gatedgcn
  - pool_cfg: global_pool
  - head_cfg: graph_prediction_head
  - _self_

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: false
depth: 3
hidden_channels: 300

encoder_cfg:
  linear_node_enc:
    out_channels: ${model.hidden_channels}
  linear_edge_enc:
    out_channels: ${model.hidden_channels}

pool_cfg:
  aggr: add

