_target_: deepreaction.model.mpnn.MPNN
_recursive_: False

defaults:
  - encoder_cfg:
    - linear_node_enc
  - layer_cfg: /mpnn_cfg/mpnn_layer
  - pool_cfg: global_pool
  - head_cfg: ffn_head
  - _self_

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: false
depth: 4
hidden_channels: 900
# layer_norm: false
# batch_norm: true

encoder_cfg:
  linear_node_enc:
    out_channels: 900

layer_cfg:
  dropout: 0.02

pool_cfg:
  aggr: add

head_cfg:
  num_layers: 2
  dropout: 0.02
  activation: relu
