_target_: deepreaction.model.gatedgcn.GatedGCN
_recursive_: False

### efficient glade
### Test MAE: 3.919298642653843
### lr 0.001
### 466,049

defaults:
  - encoder_cfg:
    - linear_node_enc
    - linear_edge_enc
  - layer_cfg: block_gatedgcn
  - pool_cfg: global_pool
  - head_cfg: graph_prediction_head
  - _self_

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: false
depth: 12
hidden_channels: 64

layer_cfg:
  residual: true
  dropout: 0.05
  activation: relu
  ffn: true

encoder_cfg:
  linear_node_enc:
    out_channels: ${model.hidden_channels}
  linear_edge_enc:
    out_channels: ${model.hidden_channels}

head_cfg:
  num_layers: 2
  dropout: 0.02
  activation: relu
