_target_: deepreaction.model.gat.GAT
_recursive_: False

# from opt_GAT

defaults:
  - encoder_cfg:
    - linear_node_enc
    - linear_edge_enc
  - layer_cfg: block_gatv2
  - pool_cfg: global_pool
  - head_cfg: graph_prediction_head
  - _self_

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: false
depth: 12
hidden_channels: 64

encoder_cfg:
  linear_node_enc:
    out_channels: ${model.hidden_channels}
  linear_edge_enc:
    out_channels: ${model.hidden_channels}

layer_cfg:
  layer_norm: false
  batch_norm: false
  residual: true
  dropout: 0.05
  ffn: true
  mpnn_cfg:
    dropout: ${model.layer_cfg.dropout}
    heads: 4


pool_cfg:
  aggr: add

head_cfg:
  num_layers: 2
  dropout: 0.02
