_target_: deeprxn.model.dmpnn.DMPNN
_recursive_: False

#### volcanic capybara
#### Test MAE: 4.03
#### lr: 0.001
#### total params: 305,921

defaults:
  - encoder_cfg:
    - node_to_edge_enc
  - layer_cfg: block_dmpnn
  - pool_cfg: global_pool
  - head_cfg: ffn_head
  - _self_

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: false
depth: 3
hidden_channels: 128

layer_cfg:
  layer_norm: false
  batch_norm: false
  residual: true
  dropout: 0.1
  activation: relu
  ffn: true

pool_cfg:
  aggr: add

head_cfg:
  num_layers: 2
  dropout: 0.02
  activation: relu
