_target_: deepreaction.model.gine.GINE
_recursive_: False

### usual oath
### Test MAE: 3.9561603070881826
### lr 0.0005
### total params 427,265

defaults:
  - encoder_cfg:
    - linear_node_enc
    - linear_edge_enc
  - layer_cfg: block_gine
  - pool_cfg: global_pool
  - head_cfg: ffn_head
  - _self_

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: false
depth: 12
hidden_channels: 128

encoder_cfg:
  linear_node_enc:
    out_channels: ${model.hidden_channels}
  linear_edge_enc:
    out_channels: ${model.hidden_channels}

layer_cfg:
  layer_norm: false
  batch_norm: false
  residual: true
  dropout: 0.05
  activation: identity
  ffn: false

pool_cfg:
  aggr: add

head_cfg:
  num_layers: 2
  dropout: 0.02
  activation: relu
