_target_: deeprxn.model.gcn.GCN
_recursive_: False

### summer night
### Test MAE: 4.425186367955172
### lr 0.001
### total params 198,017

defaults:
  - encoder_cfg:
    - linear_node_enc
    - linear_edge_enc
  - layer_cfg: block_gcn
  - pool_cfg: global_pool
  - head_cfg: ffn_head
  - _self_

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: false
depth: 9
hidden_channels: 64

layer_cfg:
  layer_norm: false
  batch_norm: false
  residual: true
  dropout: 0.05
  activation: relu
  ffn: true

encoder_cfg:
  linear_node_enc:
    out_channels: ${model.hidden_channels}
  linear_edge_enc:
    out_channels: ${model.hidden_channels}

pool_cfg:
  aggr: add

head_cfg:
  num_layers: 2
  dropout: 0.02
  activation: relu
