_target_: deeprxn.data.construct_loader
_recursive_: False

defaults:
  - dataset_cfg: e2
  - featurizer_cfg: standard
  - representation_cfg: dmg
  - transform_cfg: null
  - _self_

batch_size: 50
num_workers: 0
#pin_memory: true
cache_graphs: true
max_cache_size: null
preprocess_all: true
# no_reverse_edge: true  # Moved from root
# use_self_loop: "only"  # Moved from root
