defaults:
  - dataset_cfg: rdb7
  - representation_cfg: cgr
  - transform_cfg: null             # Specify list of transforms
  - dataset_transform_cfg: null     # Specify list of dataset_transforms
  - _self_

batch_size: 50
num_workers: 0
