_target_: deepreaction.dataset.token_dataset.TokenDataset
_partial_: true

defaults:
  - representation: simple_token

transform: null
subsample: 1         
# preprocess_all: true
# cache_graphs: true 
# max_cache_size: null
