_target_: deeprxn.representation.cgr.CGR
_recursive_: False
_partial_: True

defaults:
  - featurizer_cfg: standard

in_channel_multiplier: 2
concat_transform_features: False
pre_transform_cfg: null     # TODO: Remove this?
