_target_: deeprxn.layer.att_layer.deeprxn_att_layer.DeepRXNAttLayer
in_channels: ${model.hidden_channels}
out_channels: ${model.hidden_channels}
num_heads: 4
dropout: 0.5
batch_first: true
layer_norm: ${model.layer_cfg.layer_norm}
batch_norm: ${model.layer_cfg.batch_norm}
