# main config 

defaults:
  - data_ingestor: rdb7new
  - dataset: graph
  - dataloader: pyg_dataloader
  - model: pna
  - trainer: default
  - routine: regression_legacy
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

# LOGGING (Weight and Biases)
log: false
project_name: deepreaction
group_name: null
run_name: null

# INITIALIZATION
seed: 0

parameter_limit: null

# TODO: Bad practice, find a proper solution to pass these dataset
# properties to the model/routine
runtime_agrs_from_train_dataset_props:
  # - fp_length
  - degree_statistics
  - num_node_features
  - num_edge_features
  - mean
  - std

# DEVICE (deprecated)
use_cuda: true
device: gpu

# MODEL LOADING (deprecated)
use_loaded_model: false
pretrained_path: null

# TODO: What is this used for?
hydra:
  output_subdir: null
  run:
    dir: .
