defaults:
  - _self_
  - model: gnn.yaml
  - data: e2.yaml
  - features: features.yaml
  - transformation: transformation.yaml
  - data_loader: data_loader.yaml
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

seed: 0
epochs: 30
learning_rate: 0.001
mode: train
patience: 10
min_delta: 0.001
use_cuda: true
device: gpu
save_model: false
project_name: deeprxn

wandb: false

model_path: model.pt

hydra:
  output_subdir: null
  run:
    dir: .
