# main config 

defaults:
  - data_cfg: e2_cgr
  - model_cfg: dmpnn
  - task_cfg: regression
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_ # placement of this matters

# WANDB
wandb: false
project_name: deeprxn
group_name: null
run_name: null

# INITIALIZATION
seed: 0 # use 0

# DEVICE (redunadant)
use_cuda: true
device: gpu

# FOR SWEEPING
parameter_limit: null

# lambda_param: 0.1
# extra_loss: null
# margin: 1

# MODEL LOADING
use_loaded_model: false
pretrained_path: null

# THIS NEEDS TO GO
num_node_features: ???
num_edge_features: ???

hydra:
  output_subdir: null
  run:
    dir: .
