# main config 

defaults:
  - data_cfg: rdb7_cgr
  - model_cfg: dmpnn
  - task_cfg: regression
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_ # placement of this matters

# WANDB
wandb: false
project_name: deepreaction
group_name: null
run_name: null

# INITIALIZATION
seed: 0 # use 0

# RUNTIME ARGS
runtime_model_init_args_from_dataset:
  # degree_statistics: degree_statistics
  # in_channels: fp_length
update_cfg_from_dataset:
  # fp_length: fp_length
  num_node_features: num_node_features
  num_edge_features: num_edge_features

# DEVICE (redunadant)
use_cuda: true
device: gpu

# FOR SWEEPING
parameter_limit: null

# lambda_param: 0.1
# extra_loss: null
# margin: 1

# MODEL LOADING
use_loaded_model: false
pretrained_path: null

hydra:
  output_subdir: null
  run:
    dir: .
