# main config 

defaults:
  - data_pipeline: rdb7
  - dataset: graph
  - dataloader: pyg_dataloader
  - model: gcn
  - trainer: default
  - routine: regression
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

# WANDB
wandb: false
project_name: deepreaction
group_name: null
run_name: null

# INITIALIZATION
seed: 0 # use 0

runtime_config_parameters_from_dataset:
  # - fp_length
  # - degree_statistics
  - num_node_features
  - num_edge_features

# DEVICE (redunadant)
use_cuda: true
device: gpu

# FOR SWEEPING
parameter_limit: null

# lambda_param: 0.1
# extra_loss: null
# margin: 1

# MODEL LOADING
use_loaded_model: false
pretrained_path: null

hydra:
  output_subdir: null
  run:
    dir: .
