# main config 

defaults:
  - data: e2_cgr
  - model: dmpnn
  - optimizer: adam
  - scheduler: constant
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_ # placement of this matters

wandb: false
mode: train # train, finetune or predict
project_name: deeprxn
seed: 0 # use 0
use_cuda: true
device: gpu

under_parameters: null
group_name: null

save_model: false
model_path: pretrained/
pretrained_path: null

epochs: 30
patience: 10
min_delta: 0.01
clip_grad_norm: true
clip_grad_norm_value: 1

num_node_features: ???
num_edge_features: ???

hydra:
  output_subdir: null
  run:
    dir: .
