# main config 

defaults:
  - data_cfg: e2_cgr
  - model_cfg: dmpnn
  - task_cfg: regression
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_ # placement of this matters

wandb: false
project_name: deepreaction
seed: 0 # use 0
use_cuda: true
device: gpu

under_parameters: null
group_name: null
run_name: null

# lambda_param: 0.1
# extra_loss: null
# margin: 1

use_loaded_model: false
pretrained_path: null

num_node_features: ???
num_edge_features: ???

hydra:
  output_subdir: null
  run:
    dir: .
