_target_: deeprxn.data_old.construct_loader

dataset_name: barriers_rdb7
batch_size: 50
num_workers: 0
mode: rxn

representation: CGR # connected_pair, connected_pair_only_dummy
connection_direction: bidirectional # reactants_to_products and products_to_reactants

dummy_node: null # global, all_separate, reactant_product
dummy_connection: to_dummy # bidirectional, from_dummy, to_dummy
dummy_dummy_connection: bidirectional # bidirectional, null
dummy_feat_init: zeros # zeros, ones TODO: look into this

atom_featurizer: "atom_rdkit_organic"
bond_featurizer: "bond_rdkit_base"
