_target_: deeprxn.encoder.linear_enc.LinearEncoder
node_in_channels: ${num_node_features}
node_out_channels: ${model.mpnn_cfg.in_channels}
edge_in_channels: ${num_edge_features}
edge_out_channels: ${model.mpnn_cfg.in_channels}
