_target_: deeprxn.model.custom_model.CustomModel
_recursive_: False

defaults:
  - encoder_cfg: simple_enc
  - mpnn_cfg: gat_layer
  - att_layer_cfg: att_layer
  - pool_cfg: global_pool
  - head_cfg: ffn_head
  - _self_

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: true
mpnn_depth: 3
att_depth: 1
hidden_channels: 300

# easily override defaults
att_layer_cfg:
  attention: reactants_products

# pool_cfg:
#   pool_type: reactants
#   aggr: add
