_target_: deepreaction.model.dmpnn.DMPNN

defaults:
  - encoder: node_to_edge_enc
  - layer: dmpnn_block
  - pool: global_pool
  - head: mlp

depth: 3
edge_to_node_in_channels: ${eval:'${num_node_features} + ${model.layer.hidden_channels}'}
edge_to_node_out_channels: ${model.layer.hidden_channels}
