_target_: deeprxn.model.dmpnn_rwpe.DMPNNRWPE
_recursive_: False

defaults:
  - encoder_cfg:
    - rwpe_enc_dmpnn
  - layer_cfg: /mpnn_cfg/dmpnn_layer
  - att_layer_cfg: null
  - pool_cfg: global_pool
  - head_cfg: ffn_head
  - _self_

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: true
mpnn_depth: 3
hidden_channels: 300

# easily override defaults
mpnn_cfg:
  separate_nn: false
  dropout: 0.02

pool_cfg:
  aggr: add

head_cfg:
  num_layers: 2
  dropout: 0.02
  activation: relu
