_target_: deeprxn.model.dmpnn_gps.DMPNNGPS
_recursive_: False

defaults:
  - encoder_cfg:
    - linear_node_enc
    - node_to_edge_enc
    #- equivstable_enc
    - rwpe_enc
    #- lappe_enc
  - layer_cfg: dmpnn_gps_layer
  - pool_cfg: global_pool
  - head_cfg: ffn_head
  - _self_

# pool_cfg:
#   pool_type: reactants
#   aggr: add

encoder_cfg:
  linear_node_enc:
    out_channels: 104
  node_to_edge_enc:
    in_channels: ${eval:'${model.encoder_cfg.linear_node_enc.out_channels} + ${num_edge_features}'}
    out_channels: ${model.hidden_channels}
  rwpe_enc:
    out_channels: 24
  # lappe_enc:
  #   out_channels: 8
  # equivstable_enc:
  #   out_channels: ${model.hidden_channels}

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: false
depth: 10
hidden_channels: 128
