_target_: deeprxn.model.dmpnn.DMPNN
_recursive_: False

defaults:
  - encoder_cfg:
    - node_to_edge_enc
  - layer_cfg: /mpnn_cfg/dmpnn_layer
  - pool_cfg: global_pool
  - head_cfg: ffn_head
  - _self_

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: false
depth: 3
hidden_channels: 300

# easily override defaults
layer_cfg:
  separate_nn: false
  dropout: 0.02

pool_cfg:
  aggr: add

head_cfg:
  num_layers: 2
  dropout: 0.02
  activation: relu
