defaults:
  - layer: gat
  - pool: global
  - head: ffn_head
  - _self_

_target_: deeprxn.model.gat_model.GATModel
in_channels: 128
hidden_channels: 256
out_channels: 1
num_layers: 3

layer:
  _target_: deeprxn.layer.GATLayer
  heads: 4
  dropout: 0.1
  concat: true

pool:
  _target_: deeprxn.pool.GlobalPool
  aggr: mean
