_target_: deeprxn.model.GAT

defaults:
  - _self_

react_prod_att_cfg:
  layer_norm: true
  batch_norm: false
  num_heads: 1
  dropout: 0.02

gat_cfg:
  num_heads: 3
  dropout: 0.02
  skip_drop: True

num_node_features: null
num_edge_features: null

shared_weights: false

depth: 3
dropout: 0.02
pool_type: global
hidden_size: 300
double_features: false
attention: null # reactants_products, reactants, products
attention_depth: 1
