_target_: deepreaction.model.gnn.GNN

defaults:
  - encoder: linear_enc
  - layer: gatedgcn_block
  - pool: global_pool
  - head: mlp

depth: 12

encoder:
  _target_: torch.nn.Sequential
  _args_:
  - _target_: deepreaction.encoder.linear_node_enc.LinearNodeEncoder
    in_channels: ${num_node_features}
    out_channels: ${model.layer.hidden_channels}
    bias: true
  - _target_: deepreaction.encoder.linear_edge_enc.LinearEdgeEncoder
    in_channels: ${num_edge_features}
    out_channels: ${model.layer.hidden_channels}
    bias: true

layer:
  _target_: deepreaction.layer.gnn_block.GNNBlockLayer
  use_residual: false  # MPNN layer has its own residual
  use_ffn: true
  dropout: 0.05
  act: relu
  norm: null
  hidden_channels: 64
  mpnn:
    _target_: deepreaction.layer.mpnn_layer.gatedgcn_layer.GatedGCNLayer
    in_channels: ${model.layer.hidden_channels}
    out_channels: ${model.layer.hidden_channels}
    dropout: ${..dropout}
    act: ${..act}
    use_residual: true
    equivstable_pe: false


head:
  in_channels: ${model.layer.hidden_channels}
  hidden_size: ${model.layer.hidden_channels}
