_target_: deeprxn.model.gine.GINE
_recursive_: False

defaults:
  - encoder_cfg:
    - linear_node_enc
    - linear_edge_enc
    - equivstable_enc
    #- rwpe_enc
    #- lappe_enc
  - layer_cfg: /mpnn_cfg/gatedgcn_layer
  - att_layer_cfg: null
  - pool_cfg: global_pool
  - head_cfg: ffn_head
  - _self_

encoder_cfg:
  linear_node_enc:
    out_channels: ${model.hidden_channels}
  linear_edge_enc:
    out_channels: ${model.hidden_channels}
  # rwpe_enc:
  #   out_channels: 20
  # lappe_enc:
  #   out_channels: 8
  equivstable_enc:
    out_channels: ${model.hidden_channels}

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: false
mpnn_depth: 8
hidden_channels: 64
