_target_: deeprxn.model.gine.GINE
_recursive_: False

defaults:
  - encoder_cfg:
    - linear_node_enc
    - linear_edge_enc
    - equivstable_enc
    - rwpe_enc
    - lappe_enc
  - layer_cfg: /mpnn_cfg/gatedgcn_layer
  - pool_cfg: global_pool
  - head_cfg: ffn_head
  - _self_

encoder_cfg:
  linear_node_enc:
    out_channels: 96
  linear_edge_enc:
    out_channels: ${model.hidden_channels}
  rwpe_enc:
    out_channels: 24
  lappe_enc:
    out_channels: 8
  equivstable_enc:
    out_channels: ${model.hidden_channels}

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: false
depth: 3
hidden_channels: 128
