_target_: deepreaction.model.gnn.GNN


defaults:
  - encoder: linear_enc
  - pool: global_pool
  - head: mlp

gnn:
  _target_: deepreaction.layer.utils.Stack
  _recursive_: false
  depth: 9
  layer:
    _target_: deepreaction.layer.gnn_block.GNNBlockLayer
    use_residual: true
    use_ffn: true
    dropout: 0.05
    act: relu
    norm: null
    hidden_channels: 64
    mpnn:
      _target_: deepreaction.layer.mpnn_layer.gatv2_layer.GATv2Layer
      in_channels: ${model.gnn.layer.hidden_channels}
      out_channels: ${model.gnn.layer.hidden_channels}