_target_: deeprxn.model.GNN

defaults:
  - _self_
  - layer_cfg:
    - dmpnn_conv.yaml
    - trans_conv.yaml
  
num_node_features: null
num_edge_features: null

depth: 3
dropout: 0.02
pool_type: global
pool_real_only: false
hidden_size: 300
double_features: false
attention: null
fast_attention: false
use_attention_agg: false
use_attention_agg_heads: 1
