_target_: deeprxn.model.hybrid.Hybrid
_recursive_: False

defaults:
  - encoder_cfg: simple_enc
  - mpnn_cfg: dmpnn_layer
  - att_layer_cfg: att_layer
  - pool_cfg: global_pool
  - head_cfg: ffn_head
  - _self_

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: true
mpnn_depth: 6
hidden_channels: 1800

att_layer_depth: 1

# easily override defaults
mpnn_cfg:
  separate_nn: false
  dropout: 0.05

pool_cfg:
  aggr: mean

head_cfg:
  num_layers: 2
  dropout: 0.05
  activation: relu
