_target_: deeprxn.model.masked.Masked
_recursive_: False

defaults:
  - encoder_cfg:
    - linear_node_enc
    #- node_origins_enc
    #- linear_edge_enc
    #- equivstable_enc
    - rwpe_enc
    #- lappe_enc
  - layer_cfg: masked_att_layer
  - pool_cfg: pma
  - head_cfg: ffn_head
  - _self_

layers: [local, local, local, local, local, local, inter, inter] #["intra","inter","compound","local_inter","local_compound_inter","local_compound",
separate: true
separate_pool: false
residual: false

dmpnn_depth: 1

pool_cfg:
  num_decoder_blocks: 1

head_cfg:
  in_channels: 256
  hidden_channels: 256

encoder_cfg:
  linear_node_enc:
    out_channels: 104
  # node_origins_enc:
  #   out_channels: 8
  # linear_edge_enc:
  #   out_channels: ${model.hidden_channels}
  rwpe_enc:
    in_channels: 20
    out_channels: 24
  # lappe_enc:
  #   in_channels: 8
  #   out_channels: 16
  # equivstable_enc:
  #   out_channels: ${model.hidden_channels}

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: false
hidden_channels: 128
