_target_: deeprxn.model.gps.GPS
_recursive_: False

defaults:
  - encoder_cfg:
    - linear_node_enc
    - linear_edge_enc
    - node_origins_enc
    - edge_origins_enc
    #- equivstable_enc
    - rwpe_enc
    #- lappe_enc
  - layer_cfg: reaction_gps_layer
  - pool_cfg: global_pool
  - head_cfg: ffn_head
  - _self_

# pool_cfg:
#   pool_type: reactants
#   aggr: add

layer_cfg:
  att_layer_cfg:
    attention: reactants

encoder_cfg:
  linear_node_enc:
    out_channels: 84
  linear_edge_enc:
    out_channels: 108
  node_origins_enc:
    out_channels: 20
  edge_origins_enc:
    out_channels: 20
  rwpe_enc:
    out_channels: 24
  # lappe_enc:
  #   out_channels: 8
  # equivstable_enc:
  #   out_channels: ${model.hidden_channels}

num_node_features: ${num_node_features}
num_edge_features: ${num_edge_features}
shared_weights: false
depth: 10
hidden_channels: 128
