linear_enc:
  _target_: deepreaction.encoder.linear_enc.LinearEncoder
  node_in_channels: ${num_node_features}
  node_out_channels: ${model_cfg.layer_cfg.mpnn_cfg.in_channels}
  edge_in_channels: ${num_edge_features}
  edge_out_channels: ${model_cfg.layer_cfg.mpnn_cfg.in_channels}
