_target_: deeprxn.data.construct_loader

dataset_name: ${data.dataset_name}
batch_size: 50
num_workers: 0
mode: rxn

representation: CGR # connected_pair, connected_pair_only_dummy
connection_direction: null # reactants_to_products and products_to_reactants

dummy_node: null # global, all_separate, reactant_product
dummy_connection: to_dummy # bidirectional, from_dummy, to_dummy
dummy_dummy_connection: bidirectional # bidirectional, null
dummy_feat_init: zeros # zeros, ones TODO: look into this

atom_featurizer: ${features.atom_featurizer}
bond_featurizer: ${features.bond_featurizer}
