# main config 
wandb: false
project_name: exp7
seed: 0
use_cuda: true
device: gpu
under_parameters: null
group_name: masked
run_name: null 
use_loaded_model: false
pretrained_path: null
num_node_features: ???
num_edge_features: ???

data_cfg:
  _target_: deepreaction.data.construct_loader
  _recursive_: False
  batch_size: 50
  num_workers: 0
  cache_graphs: true
  max_cache_size: null
  preprocess_all: true
  dataset_cfg:
    _target_: deepreaction.data.load_csv_dataset
    input_column: "rxn_smiles"
    target_column: "ea"
    data_folder: "barriers_rdb7new"
    reduced_dataset: 1
    train_ratio: 0.9
    val_ratio: 0.05
    test_ratio: 0.05
    use_pickle: true
    seed_index: 0
    enthalpy_column: "dh"
  featurizer_cfg:
    bond_featurizer_cfg:
      _target_: deepreaction.featurizer.bond_featurizer.bond_rdkit_base.RDKitBaseBondFeaturizer
    atom_featurizer_cfg:
      _target_: deepreaction.featurizer.atom_featurizer.atom_rdkit_organic.RDKitOrganicAtomFeaturizer
  representation_cfg:
    _target_: deepreaction.representation.line_dmg.LineDMG
    _recursive_: False
    in_channel_multiplier: 1
    concat_origin_feature: false
    pre_transform_cfg: null
    use_directed: true
    feature_aggregation: null
  transform_cfg:
    randomwalk:
      _target_: deepreaction.transform.randomwalkpe.RandomWalkPETransform
      walk_length: 20
      attr_name: randomwalkpe
      type: graph

model_cfg:
  _target_: deepreaction.model.masked_dmg.MaskedDMG
  _recursive_: False
  num_node_features: ${num_node_features}
  num_edge_features: ${num_edge_features}
  hidden_channels: 128
  layers: [local, local, local, local, local, inter, inter, inter] 
  separate: false
  encoder_cfg:
    linear_node_enc:
      _target_: deepreaction.encoder.linear_node_enc.LinearNodeEncoder
      in_channels: ${num_node_features}
      out_channels: ${eval:'${model_cfg.hidden_channels} - ${model_cfg.encoder_cfg.rwpe_enc.out_channels}'}
      bias: true
    rwpe_enc:
      _target_: deepreaction.encoder.rwpe_enc.RWEncoder
      in_channels: ${data_cfg.transform_cfg.randomwalk.walk_length}
      out_channels: 24
      transform_type: normal
  layer_cfg:
    _target_: deepreaction.layer.att_layer.masked_att_layer.MaskedAttLayer
    _partial_: true
    embed_dim: ${model_cfg.hidden_channels}
    mode: local
    num_heads: 4
    dropout: 0.05
    batch_first: true
    layer_norm: false
    batch_norm: true
  pool_cfg:
    _target_: deepreaction.pool.pool.GlobalPool
    aggr: add
  head_cfg:
    _target_: deepreaction.head.ffn_head.FFNHead
    in_channels: ${model_cfg.hidden_channels}
    out_channels: 1
    hidden_channels: ${model_cfg.hidden_channels}
    num_layers: 2
    dropout: 0.02
    activation: relu

task_cfg:
  _target_: deepreaction.task.regression.train
  _recursive_: False
  clip_grad_norm: true
  clip_grad_norm_value: 1
  min_delta: 0.01
  save_model_parameters: false
  model_path: null
  use_wandb: ${wandb}
  epochs: 200
  patience: 30
  loss_cfg:
    _target_: deepreaction.loss.mse.MSELoss
    reduction: sum
  optimizer_cfg:
    _target_: torch.optim.AdamW
    _partial_: true
    weight_decay: 1e-2
    amsgrad: false
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1e-8
    foreach: null
    maximize: false
    capturable: false
  scheduler_cfg:
    scheduler:
      _target_: torch.optim.lr_scheduler.LambdaLR
      _partial_: true
      lr_lambda:
        _target_: deepreaction.scheduler.scheduler.get_cosine_scheduler_with_warmup
        num_warmup_steps: 10
        num_training_steps: ${task_cfg.epochs}
        num_cycles: 0.5

hydra:
  output_subdir: null
  run:
    dir: .
