_target_: deepreaction.dataset.mol_graph_dataset.MolGraphDataset
_partial_: true

# === DATA PIPELINE ===================================
defaults:
  # Data pipeline components in chronological order
  - data_source_cfg: split_csv_source
  - preprocessing_cfg/column_mapper_cfg: column_filter_rename
  - _self_ 

# === DATA PIPELINE COMPONENTS ========================
data_folder: "deepreaction_datasets/data/cycloaddition/barriers"

# === DATASET =========================================
input_column: "rxn_smiles"
target_column: "G_act"
# Additional dataset arguements (see MolGraphDataset for details)
# subsample: null         
# cache_graphs: true 
# max_cache_size: null
# preprocess_all: true