_target_: deeprxn.dataset.mol_graph_dataset.MolGraphDataset
_partial_: true

# === DATA PIPELINE ===================================
defaults:
  # Data pipeline components in chronological order
  - pipeline_component/data_reader_cfg: split_csv_reader
  - _self_ 

# === DATA PIPELINE COMPONENTS ========================
data_folder: "deeprxn_datasets/data/cycloaddition/barriers"

# === DATASET =========================================
input_column: "rxn_smiles"
target_column: "G_act"
# Additional dataset arguements (see MolGraphDataset for details)
# subsample: null         
# cache_graphs: true 
# max_cache_size: null
# preprocess_all: true