_target_: deepreaction.dataset.fingerprint_dataset.FingerprintDataset
_partial_: true

# === DATA PIPELINE ===================================
defaults:
  # Data pipeline components in chronological order
  - data_source_cfg: single_csv_source
  - preprocessing_cfg/data_splitter_cfg: index_splitter
  - preprocessing_cfg/column_mapper_cfg: column_filter_rename
  - _self_

# === DATA PIPELINE COMPONENTS ========================
# For single_csv_source
data_folder: "data/barriers_rdb7new"
data_file: "data.csv"
# For index_splitter
split_index_path: "data/barriers_rdb7new/seed${data_cfg.dataset_cfg.seed}.pkl"
seed: 0
# For column_filter_rename
column_mapping:
  smiles: "rxn_smiles"
  label: "ea"

# === DATASET =========================================
# Additional dataset arguements (see GraphDataset for details)
# preprocess_all: true
# cache_graphs: true 
# max_cache_size: null
subsample: 0.01         
