_target_: deeprxn.dataset.mol_graph_dataset.MolGraphDataset

data_path: "data/barriers_rdb7new_3"

input_column: "smiles"
target_column: "dE0"

subsample: null   # TODO: Remove if not used

data_pipeline_cfg:
  _target_: deeprxn.data.DataPipeline
  modules:
    - single_csv_reader
    - ration_splitter