_target_: deeprxn.dataset.mol_graph_dataset.MolGraphDataset

data_path: "data/barriers_rdb7"

input_column: "smiles"
target_column: "ea"

cache_graphs: true
max_cache_size: null
preprocess_all: true

subsample: null   # TODO: Remove if not used

data_pipeline_cfg:
  _target_: deeprxn.data.DataPipeline
  modules:
    - single_csv_reader
    - ration_splitter