_target_: deeprxn.dataset.graph_dataset.GraphDataset
_partial_: true

# === DATA PIPELINE ===================================
defaults:
  # Data pipeline components in chronological order
  - pipeline_component/data_reader_cfg: single_csv_reader
  - pipeline_component/data_splitter_cfg: ratio_splitter
  - _self_

# === DATA PIPELINE COMPONENTS ========================
# For single_csv_reader
data_folder: "deeprxn_datasets/data/rdb7/barriers"
data_file: "rdb7_full.csv"
# For ratio_splitter
train_ratio: 0.9
val_ratio: 0.05
test_ratio: 0.05

# === DATASET =========================================
column_mapping:
  smiles: "smiles"
  label: "dE0"
# Additional dataset arguements (see GraphDataset for details)
# preprocess_all: true
# cache_graphs: true 
# max_cache_size: null
# subsample: null         
