_target_: deeprxn.dataset.mol_graph_dataset.MolGraphDataset

# === DATA PIPELINE ===================================
defaults:
  # Data pipeline components in chronological order
  - pipeline_components/data_reader_cfg: single_csv_reader
  - pipeline_components/data_splitter_cfg: ratio_splitter
  - _self_

# === DATA PIPELINE COMPONENTS ========================
# For single_csv_reader
data_folder: "deeprxn_datasets/data/rdb7/barriers"
data_file: "rdb7_full.csv"
# For ratio_splitter
train_ratio: 0.9
val_ratio: 0.05
test_ratio: 0.05

# === DATASET =========================================
input_column: "rxn_smiles"
target_column: "ea"
# Additional dataset arguements (see MolGraphDataset for details)
# subsample: null         
# cache_graphs: true 
# max_cache_size: null
# preprocess_all: true
