_target_: deeprxn.data.load_csv_dataset
input_column: "rxn_smiles"
target_column: "ea"
data_folder: "barriers_rdb7low"
reduced_dataset: 1
train_ratio: 0.9
val_ratio: 0.05
test_ratio: 0.05
use_pickle: true
seed_index: 0
enthalpy_column: "dh"
