_target_: deeprxn.dataset.graph_dataset.GraphDataset
_partial_: true

# === DATA PIPELINE ===================================
defaults:
  # Data pipeline components in chronological order
  - source_pipeline_cfg/data_reader_cfg: single_csv_reader
  - source_pipeline_cfg/data_splitter_cfg: ratio_splitter
  - source_pipeline_cfg/column_mapper_cfg: column_filter_rename
  - _self_

# === DATA PIPELINE COMPONENTS ========================
# For single_csv_reader
data_folder: "deeprxn_datasets/data/rdb7/barriers"
data_file: "rdb7_full.csv"
# For ratio_splitter
train_ratio: 0.9
val_ratio: 0.05
test_ratio: 0.05
# For column_filter_rename
column_mapping:
  smiles: "smiles"
  label: "dE0"

# === DATASET =========================================
# TODO: Move sample_transform_cfg and dataset_transform_cfg here
# Additional dataset arguements (see GraphDataset for details)
# preprocess_all: true
# cache_graphs: true 
# max_cache_size: null
# subsample: null         
