_target_: deeprxn.dataset.mol_graph_dataset.MolGraphDataset

data_folder: "barriers_rgd1"

input_column: "smiles"
target_column: "ea"

subsample: null   # TODO: Remove if not used

data_pipeline_cfg:
  _target_: deeprxn.data.DataPipeline
  modules:
    - single_csv_reader
    - ration_splitter