_target_: deeprxn.dataset.mol_graph_dataset.MolGraphDataset

# === DATA PIPELINE ===================================
defaults:
  # Data pipeline components in chronological order
  - pipeline_components/data_reader_cfg: split_csv_reader
  - _self_ 

# === DATA PIPELINE COMPONENTS ========================
data_folder: "deeprxn_datasets/data/rgd1/barriers"

# === DATASET =========================================
input_column: "smiles"
target_column: "ea"
# Additional dataset arguements (see MolGraphDataset for details)
# subsample: null         
# cache_graphs: true 
# max_cache_size: null
# preprocess_all: true