_target_: deeprxn.data.dataset.mol_graph_dataset.MolGraphDataset
_partial_: true

# === DATA PIPELINE ===================================
defaults:
  # Data pipeline components in chronological order
  - source_pipeline_cfg/data_reader_cfg: split_csv_reader
  - source_pipeline_cfg/column_mapper_cfg: column_filter_rename
  - _self_ 

# === DATA PIPELINE COMPONENTS ========================
data_folder: "deeprxn_datasets/data/e2sn2/Sn2/barriers"

# === DATASET =========================================
input_column: "AAM"
target_column: "ea" 
# Additional dataset arguements (see MolGraphDataset for details)
# subsample: null         
# cache_graphs: true 
# max_cache_size: null
# preprocess_all: true
