_target_: deepreaction.scheduler.cosine_with_warmup_lr.CosineWithWarmupLR
_partial_: true       # optimizer passed at runtime

num_warmup_steps: 50          # Number of warmup steps (set as needed)
num_training_steps: 1000000   # Large value to approximate "no upper bound"
eta_min: 0.0 
start_factor: 1e-6
end_factor: 1.0