_target_: deepreaction.layer.block_gcn.BlockGCNLayer
_recursive_: False

defaults:
  - mpnn_cfg: gcn_layer

hidden_channels: ${model_cfg.hidden_channels}
in_channels: ${model_cfg.hidden_channels}
out_channels: ${model_cfg.hidden_channels}

layer_norm: false
batch_norm: false
residual: true
dropout: 0.0
activation:
  _target_: torch.nn.ReLU
  inplace: true
ffn: false
