_target_: deeprxn.layer.block_gatedgcn.BlockGatedGCNLayer
_recursive_: False

defaults:
  - mpnn_cfg: gatedgcn_layer

hidden_channels: ${model.hidden_channels}
in_channels: ${model.hidden_channels}
out_channels: ${model.hidden_channels}

residual: true
dropout: 0.0
activation: relu
ffn: false

mpnn_cfg:
  residual: ${model.layer_cfg.residual}
  act: ${model.layer_cfg.activation}
  dropout: ${model.layer_cfg.dropout}

