_target_: deepreaction.layer.block_dmpnn.BlockDMPNNLayer
_recursive_: False

defaults:
  - mpnn_cfg: dmpnn_layer

hidden_channels: ${model_cfg.hidden_channels}
in_channels: ${model_cfg.hidden_channels}
out_channels: ${model_cfg.hidden_channels}

layer_norm: false
batch_norm: false
residual: true
dropout: 0.0
activation: relu
ffn: false

