_target_: deepreaction.layer.block_gatedgcn.BlockGatedGCNLayer
_recursive_: False

defaults:
  - mpnn_cfg: gatedgcn_layer

hidden_channels: ${model_cfg.hidden_channels}
in_channels: ${model_cfg.hidden_channels}
out_channels: ${model_cfg.hidden_channels}

residual: true
dropout: 0.0
activation:
  _target_: torch.nn.ReLU
  inplace: true
ffn: false

mpnn_cfg:
  residual: ${model_cfg.layer_cfg.residual}
  act: ${model_cfg.layer_cfg.activation}
  dropout: ${model_cfg.layer_cfg.dropout}

