_target_: deepreaction.layer.block_pna.BlockPNALayer
_recursive_: False

defaults:
  - mpnn_cfg: pna_layer

hidden_channels: ${model_cfg.hidden_channels}
in_channels: ${model_cfg.hidden_channels}
out_channels: ${model_cfg.hidden_channels}

layer_norm: false
batch_norm: false
residual: true
dropout: 0.0
activation:
  _target_: torch.nn.ReLU
  inplace: true
ffn: false

mpnn_cfg:
  aggregators: ['mean', 'max', 'sum'] # ['mean', 'max', 'min', 'std']
  scalers: ['identity'] # ['identity', 'amplification', 'attenuation']
