_target_: deeprxn.layer.block_gcn.BlockGCNLayer
_recursive_: False

defaults:
  - mpnn_cfg: gcn_layer

hidden_channels: ${model.hidden_channels}
in_channels: ${model.hidden_channels}
out_channels: ${model.hidden_channels}

layer_norm: false
batch_norm: false
residual: true
dropout: 0.0
activation: relu
ffn: false
