_target_: deepreaction.layer.deepreaction_layer.deepreactionLayer
_recursive_: False

defaults:
  - mpnn_cfg: gatedgcn_layer
  - att_layer_cfg: deepreaction_att_layer

layer_norm: False
batch_norm: True
dropout: 0.0

in_channels: ${model_cfg.hidden_channels}
out_channels: ${model_cfg.hidden_channels}
