_target_: deepreaction.layer.dmpnn_deepreaction_layer_20.DMPNNdeepreactionLayer20
_recursive_: False

defaults:
  - mpnn_cfg: dmpnn_layer
  - att_layer_cfg: transformer

layer_norm: False
batch_norm: True
dropout: 0.0

in_channels: ${model_cfg.hidden_channels}
out_channels: ${model_cfg.hidden_channels}

att_layer_cfg:
  embed_dim: ${model_cfg.hidden_channels}
  num_heads: 4
  dropout: 0.5
