none:
  _target_: deeprxn.layer.att_layer.masked_att_layer.MaskedAttLayer
  embed_dim: ${model_cfg.hidden_channels}
  num_heads: 4
  dropout: 0.5
  batch_first: true
  mode: null # none, local, intra, inter
  layer_norm: true
  batch_norm: false
