_target_: deeprxn.layer.reaction_gps_layer.ReactionGPSLayer
_recursive_: False

defaults:
  - mpnn_cfg: gatedgcn_layer
  - att_layer_cfg: reaction_gps_att_layer

layer_norm: False
batch_norm: True
dropout: 0.0

in_channels: ${model.hidden_channels}
out_channels: ${model.hidden_channels}

att_layer_cfg:
  attention: reactants_products # reactants or products or reactants_products
  num_heads: 4
  dropout: 0.5
