_target_: deeprxn.layer.rxn_gps_layer.RXNGPSLayer
_recursive_: False

defaults:
  - mpnn_cfg: gatedgcn_layer
  - att_layer_cfg: transformer

layer_norm: True
batch_norm: False
dropout: 0.0

in_channels: ${model_cfg.hidden_channels}
out_channels: ${model_cfg.hidden_channels}

att_layer_cfg:
  embed_dim: ${model_cfg.hidden_channels}
  num_heads: 1
  dropout: 0.5
