_target_: deepreaction.utils.CallableCompose

defaults:
  - data_source: pre_split_csv_source
  - column_mapper: column_filter_and_rename
  - data_splitter: null

data_source:
  data_folder: "deepreaction_datasets/data/cycloaddition/barriers"

column_mapper:
  column_mapping:
    smiles: "rxn_smiles"
    label: "G_act"
