_target_: torch_geometric.loader.DataLoader
_partial_: true

batch_size: 50

num_workers: 0
pin_memory: true

sampler: null     # torch_geometric.data.RandomNodeSampler
generator: null   # torch.Generator (how seed ?)