_target_: deepreaction.layer.mpnn_layer.gatv2_layer.GATv2Layer
in_channels: ${model_cfg.hidden_channels}
out_channels: ${eval:'${model_cfg.hidden_channels} // ${.heads}'}
heads: 1
dropout: 0.0
concat: true
use_edge_attr: true
