_target_: torch_geometric.nn.MLP
in_channels: ${model.gnn.layer.hidden_channels}      # Override in higher model config
hidden_channels: ${model.gnn.layer.hidden_channels}  # Override in higher model config
out_channels: 1
num_layers: 2
dropout: 0.02
act: relu