_target_: lightning.Trainer

default_root_dir: ./lightning_logs

logger: 
  _target_: lightning.pytorch.loggers.WandbLogger
  log_model: true

callbacks:
  - _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    min_delta: 0.01
    patience: 10
    mode: min
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    # dirpath: pretrained
    monitor: val_loss

accelerator: auto
max_epochs: -1  # -1 means no limit
gradient_clip_val: 1.0


    