_target_: deepreaction.head.ffn_enthalpy_head.FFNEnthalpyHead
in_channels: ${eval:'${model_cfg.hidden_channels} + 1'}
out_channels: 1
hidden_channels: ${eval:'${model_cfg.hidden_channels} + 1'}
num_layers: 2
dropout: 0.02
activation: relu
